---
title: "Demographics and Party Breakdowns"
author: "Aaron Kessler"
date: "10/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(lubridate)
library(readxl)
library(writexl)
library(tidycensus)
options(scipen = 999)

#load saved file with key prez states only
state_keyprezonly_bothcycles <- readRDS("processed_data/state_keyprezonly_bothcycles.rds")

```

## Gender

Growth from previous cycle

```{r pressure, echo=FALSE}

#calculate growth for each gender group
gender_states <- state_keyprezonly_bothcycles %>% 
  group_by(cycle, state, gender) %>% 
  summarise(
    total_returned = sum(ballots_returned, na.rm = TRUE)
  ) %>% 
  pivot_wider(names_from = c(cycle, gender), values_from = total_returned) %>% 
  clean_names() %>% 
  mutate(
    diff_female = x2020_female - x2016_female,
    pctchg_female = round_half_up((x2020_female - x2016_female) / x2016_female * 100, 2),
    diff_male = x2020_male - x2016_male,
    pctchg_male = round_half_up((x2020_male - x2016_male) / x2016_male * 100, 2),
    diff_unk = x2020_unknown - x2016_unknown,
    pctchg_unk = round_half_up((x2020_unknown - x2016_unknown) / x2016_unknown * 100, 2)
  ) 

#add totals for each cycle and difference
gender_states %>% 
  mutate(
    
  )

```

